apiVersion: apps/v1
kind: Deployment
metadata:
  name: mario
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mario
  template:
    metadata:
      labels:
        app: mario
    spec:
      volumes:
        - name: config-volume
          configMap:
            name: mario-config
            items:
              - key: config.yaml
                path: config.yaml
      imagePullSecrets:
        - name: my-docker-secret
      containers:
        - image: crispyduck/mario-gitops:latest
          name: mario
          volumeMounts:
            - name: config-volume
              mountPath: /app/config.yaml
              subPath: config.yaml
          envFrom:
            - configMapRef:
                name: mario-config
            - secretRef:
                name: mario-secrets
          ports:
            - containerPort: 8888
              protocol: TCP
