apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-mario
  annotations:
    cert-manager.io/cluster-issuer: my-letsencrypt-issuer
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - mario.example.com
      secretName: mario-secret
  rules:
    - host: mario.example.com
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: mario
                port:
                  number: 8888
