apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: mario-gitops
resources:
  - configmap.yaml
  - deployment.yaml
  - ingress.yaml
  - service.yaml

images:
  - name: crispyduck/mario-gitops
    newTag: "8"
